# Generated by Django 4.2.20 on 2026-06-10 00:00

import uuid

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("transactions", "0013_transfer"),
    ]

    operations = [
        migrations.CreateModel(
            name="TransferMulticurrency",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "uuid",
                    models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
                ),
                ("amount_map", models.JSONField(default=dict)),
                (
                    "transfer",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="multicurrency",
                        to="transactions.transfer",
                        to_field="uuid",
                    ),
                ),
            ],
        ),
    ]
