# Generated by Django 4.2.20 on 2026-07-06 10:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("budget", "0026_budget_from_account_budget_kind_budget_to_account_and_more"),
        ("transactions", "0015_transfer_transfer_budget"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="transfer",
            name="transfer_budget",
        ),
        migrations.AddField(
            model_name="transfer",
            name="budget",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.DO_NOTHING,
                to="budget.budget",
                to_field="uuid",
            ),
        ),
    ]
