# Generated by Django 4.2.20 on 2026-07-13 09:44

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("categories", "0017_remove_category_name_parent_null_uniq"),
    ]

    operations = [
        migrations.AlterField(
            model_name="category",
            name="type",
            field=models.CharField(
                choices=[
                    ("INC", "Income"),
                    ("EXP", "Expense"),
                    ("CAP", "Capital Expense"),
                ],
                default="EXP",
                max_length=3,
            ),
        ),
    ]
