# Generated by Django 4.2.20 on 2026-07-06 10:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("categories", "0017_remove_category_name_parent_null_uniq"),
        ("accounts", "0009_account_kind"),
        ("budget", "0025_alter_budget_recurrent_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="budget",
            name="from_account",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.DO_NOTHING,
                related_name="budgets_from_account",
                to="accounts.account",
                to_field="uuid",
            ),
        ),
        migrations.AddField(
            model_name="budget",
            name="kind",
            field=models.CharField(
                choices=[("EXPENSE", "Expense"), ("TRANSFER", "Transfer")],
                default="EXPENSE",
                max_length=20,
            ),
        ),
        migrations.AddField(
            model_name="budget",
            name="to_account",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.DO_NOTHING,
                related_name="budgets_to_account",
                to="accounts.account",
                to_field="uuid",
            ),
        ),
        migrations.AlterField(
            model_name="budget",
            name="category",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="categories.category",
                to_field="uuid",
            ),
        ),
    ]
